### ISSUE TITLE
Not working on 1.18

### ISSUE THREAD

**Issue by lucas19961** [rayzr522/JSONMessage#16]
JSONMessage is not Working on Spigot 1.18

```
[15:08:04] [Server thread/WARN]: java.lang.NoSuchMethodException: net.minecraft.server.network.PlayerConnection.sendPacket(net.minecraft.network.protocol.Packet)
[15:08:04] [Server thread/WARN]:        at java.base/java.lang.Class.getMethod(Class.java:2227)
[15:08:04] [Server thread/WARN]:        at me.rayzr522.jsonmessage.compat.impl.PlayerConnectImpl17ToFuture.<init>(PlayerConnectImpl17ToFuture.java:29)
[15:08:04] [Server thread/WARN]:        at me.rayzr522.jsonmessage.compat.ImplementationPicker.lambda$getImplementation$1(ImplementationPicker.java:29)
[15:08:04] [Server thread/WARN]:        at java.base/java.util.Optional.map(Optional.java:260)
[15:08:04] [Server thread/WARN]:        at me.rayzr522.jsonmessage.compat.ImplementationPicker.getImplementation(ImplementationPicker.java:27)
[15:08:04] [Server thread/WARN]:        at me.rayzr522.jsonmessage.compat.CompatManager.<init>(CompatManager.java:38)
[15:08:04] [Server thread/WARN]:        at me.rayzr522.jsonmessage.compat.CompatManager.get(CompatManager.java:54)
[15:08:04] [Server thread/WARN]:        at me.rayzr522.jsonmessage.compat.CompatManager.chatComponent(CompatManager.java:60)
[15:08:04] [Server thread/WARN]:        at me.rayzr522.jsonmessage.JSONMessage.send(JSONMessage.java:159)
[15:08:04] [Server thread/WARN]:        at de.lucas19961.commands.TPACommand.onCommand(TPACommand.java:37)
[15:08:04] [Server thread/WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[15:08:04] [Server thread/WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[15:08:04] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:800)
[15:08:04] [Server thread/WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1938)
[15:08:04] [Server thread/WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1777)
[15:08:04] [Server thread/WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1758)
[15:08:04] [Server thread/WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[15:08:04] [Server thread/WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:1)
[15:08:04] [Server thread/WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30)
[15:08:04] [Server thread/WARN]:        at net.minecraft.server.TickTask.run(SourceFile:18)
[15:08:04] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:151)
[15:08:04] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(SourceFile:23)
[15:08:04] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1158)
[15:08:04] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:1)
[15:08:04] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.y(SourceFile:125)
[15:08:04] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1137)
[15:08:04] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1130)
[15:08:04] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.bp(SourceFile:110)
[15:08:04] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1113)
[15:08:04] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1038)
[15:08:04] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
[15:08:04] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by rayzr522** [comment]
@lucas19961 I've built & deployed a test version of JSONMessage with a fix, available as version `1.3.1-SNAPSHOT` on Maven -- would you mind giving it a try?

it encapsulates the changes from this PR: https://github.com/rayzr522/JSONMessage/pull/17

**Comment by lucas19961** [comment]
Works Fine for me

**Comment by foxfirecodes** [comment]
awesome! I tested it more thoroughly myself as well, and it looks good to go. @lucas19961 i've merged this down and released it as `me.rayzr522:jsonmessage:1.3.1`
